import type { AquaFilePlan, AquaProjectManifest } from './types.js';

export function renderProjectFiles(manifest: AquaProjectManifest): readonly AquaFilePlan[] {
  const files: AquaFilePlan[] = [
    file('.aqua/project.json', `${JSON.stringify(manifest, null, 2)}\n`),
    file('package.json', packageJson(manifest)),
    file('pnpm-workspace.yaml', 'packages: []\n'),
    file('tsconfig.json', tsconfigJson()),
    file('README.md', readme(manifest)),
    file('src/index.ts', indexTs()),
    file('src/harness/types.ts', harnessTypesTs()),
    file('src/harness/trace.ts', traceTs()),
    file('src/harness/artifacts.ts', artifactsTs()),
    file('src/harness/guardrails.ts', guardrailsTs()),
    file('src/harness/model-provider.ts', modelProviderTs()),
    file('src/harness/permissions.ts', permissionsTs()),
    file('src/harness/verification.ts', verificationTs()),
    file('src/harness/tools.ts', toolsTs(manifest)),
    file('src/harness/runner.ts', runnerTs()),
    file('src/workflows/plan-execute-verify.ts', workflowTs(manifest)),
    ...manifest.modules.agents.map((agent) => file(`src/agents/${agent}.ts`, agentTs(agent))),
    file('tests/fakes/fake-model-provider.ts', fakeModelProviderTs()),
    file('tests/smoke.test.ts', smokeTestTs(manifest)),
  ];

  if (manifest.modules.tools.includes('artifact-recorder')) {
    files.push(file('src/tools/artifact-recorder.ts', artifactRecorderToolTs()));
  }

  return files;
}

function file(relativePath: string, content: string): AquaFilePlan {
  return { relativePath, content };
}

function packageJson(manifest: AquaProjectManifest): string {
  return `${JSON.stringify({
    name: manifest.projectName.toLowerCase().replace(/_/g, '-'),
    version: '0.1.0',
    private: true,
    type: 'module',
    scripts: {
      build: 'tsc -p tsconfig.json',
      typecheck: 'tsc -p tsconfig.json --noEmit',
      test: 'tsc -p tsconfig.json && node --test dist/tests/*.test.js',
      smoke: 'tsc -p tsconfig.json && node --test dist/tests/smoke.test.js',
      start: 'tsc -p tsconfig.json && node dist/src/index.js',
    },
    devDependencies: {
      '@types/node': '^20.11.0',
      typescript: '^5.3.0',
    },
  }, null, 2)}\n`;
}

function tsconfigJson(): string {
  return `${JSON.stringify({
    compilerOptions: {
      target: 'ES2022',
      lib: ['ES2022'],
      module: 'NodeNext',
      moduleResolution: 'NodeNext',
      strict: true,
      exactOptionalPropertyTypes: true,
      noUncheckedIndexedAccess: true,
      noUnusedLocals: true,
      noUnusedParameters: true,
      noFallthroughCasesInSwitch: true,
      moduleDetection: 'force',
      forceConsistentCasingInFileNames: true,
      skipLibCheck: true,
      declaration: true,
      sourceMap: true,
      rootDir: '.',
      outDir: 'dist',
    },
    include: ['src/**/*.ts', 'tests/**/*.ts'],
  }, null, 2)}\n`;
}

function readme(manifest: AquaProjectManifest): string {
  return `# ${manifest.projectName}

Generated by AQUA as a modular TypeScript agent harness base.

This project is intentionally honest: it does not include a hidden LLM client or a fake agent implementation. The default runtime returns \`MODEL_PROVIDER_NOT_CONFIGURED\` until you inject a real model provider.

## Contract

- Preset: \`${manifest.preset}\`
- Harness target: \`${manifest.harness}\`
- Agents: ${manifest.modules.agents.map((agent) => `\`${agent}\``).join(', ')}
- Tools: ${manifest.modules.tools.length > 0 ? manifest.modules.tools.map((tool) => `\`${tool}\``).join(', ') : 'none'}
- Workflows: ${manifest.modules.workflows.map((workflow) => `\`${workflow}\``).join(', ')}

The machine-readable project contract lives at \`.aqua/project.json\`. Keep CLI, Skill, and manual edits aligned with that file.

## Harness seams

- \`ModelProvider\`: the only seam that may call an LLM or external model.
- \`Agent\`: focused role definition that depends on \`ModelProvider\`.
- \`Tool\`: deterministic capability with permission hooks.
- \`Workflow\`: owns control flow instead of hiding it inside model calls.
- \`TraceSink\`: records run, agent, and verification events.
- \`ArtifactStore\`: captures local outputs without requiring external services.
- \`PermissionPolicy\`: blocks side-effecting tools unless explicitly allowed.
- \`Verifier\`: checks final output before a run is considered successful.

## Verify

\`\`\`bash
${manifest.commands.install}
${manifest.commands.typecheck}
${manifest.commands.test}
${manifest.commands.smoke}
\`\`\`

## Run

\`\`\`bash
${manifest.packageManager} run start -- "your input"
\`\`\`

By default this command fails with \`MODEL_PROVIDER_NOT_CONFIGURED\`. Implement or inject a real provider in \`src/harness/model-provider.ts\` before treating this as an application.
`;
}

function indexTs(): string {
  return `import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { createNotConfiguredModelProvider } from './harness/model-provider.js';
import { createRunner } from './harness/runner.js';
import type { ModelProvider } from './harness/types.js';
import { createPlanExecuteVerifyWorkflow } from './workflows/plan-execute-verify.js';

export { createRunner } from './harness/runner.js';
export type { Agent, AgentContext, AgentResult, HarnessRunInput, HarnessRunResult, ModelProvider, Tool, Workflow } from './harness/types.js';

export interface ApplicationOptions {
  readonly modelProvider?: ModelProvider;
}

export function createApplication(options: ApplicationOptions = {}) {
  return createRunner({
    modelProvider: options.modelProvider ?? createNotConfiguredModelProvider(),
    workflow: createPlanExecuteVerifyWorkflow(),
  });
}

export async function run(input: string, options: ApplicationOptions = {}) {
  return createApplication(options).run({ input });
}

const isMain = process.argv[1] ? fileURLToPath(import.meta.url) === path.resolve(process.argv[1]) : false;

if (isMain) {
  const input = process.argv.slice(2).join(' ') || 'smoke';
  const result = await run(input);
  console.log(JSON.stringify(result, null, 2));
  process.exitCode = result.success ? 0 : 1;
}
`;
}

function harnessTypesTs(): string {
  return `export interface HarnessRunInput {
  readonly input: string;
}

export interface HarnessRunResult {
  readonly success: boolean;
  readonly output: string;
  readonly errorCode?: string;
  readonly trace: readonly TraceEvent[];
  readonly artifacts: readonly Artifact[];
}

export interface AgentContext {
  readonly trace: TraceSink;
  readonly artifacts: ArtifactStore;
  readonly tools: ToolRegistry;
  readonly permissions: PermissionPolicy;
  readonly verifier: Verifier;
  readonly modelProvider: ModelProvider;
}

export interface Agent {
  readonly id: string;
  readonly role: string;
  readonly instructions: string;
  run(input: string, context: AgentContext): Promise<AgentResult>;
}

export interface AgentResult {
  readonly success: boolean;
  readonly output: string;
  readonly errorCode?: string;
}

export interface ModelRequest {
  readonly agentId: string;
  readonly role: string;
  readonly instructions: string;
  readonly input: string;
  readonly availableTools: readonly ToolDescriptor[];
}

export interface ModelResponse {
  readonly text: string;
}

export interface ModelProvider {
  generate(request: ModelRequest): Promise<ModelResponse>;
}

export interface ToolDescriptor {
  readonly id: string;
  readonly description: string;
  readonly sideEffect: ToolSideEffect;
}

export type ToolSideEffect = 'none' | 'local-filesystem' | 'network' | 'external-system';

export interface Tool extends ToolDescriptor {
  execute(input: unknown, context: AgentContext): Promise<unknown>;
}

export interface ToolRegistry {
  get(id: string): Tool | undefined;
  list(): readonly Tool[];
  describe(): readonly ToolDescriptor[];
}

export interface TraceEvent {
  readonly type: 'run.started' | 'agent.started' | 'agent.completed' | 'verification.completed' | 'run.completed';
  readonly message: string;
  readonly timestamp: string;
  readonly metadata?: Record<string, unknown>;
}

export interface TraceSink {
  record(event: Omit<TraceEvent, 'timestamp'>): void;
  list(): readonly TraceEvent[];
}

export interface Artifact {
  readonly path: string;
  readonly content: string;
}

export interface ArtifactStore {
  write(path: string, content: string): void;
  list(): readonly Artifact[];
}

export interface Workflow {
  run(input: HarnessRunInput, context: AgentContext): Promise<HarnessRunResult>;
}

export interface PermissionRequest {
  readonly toolId: string;
  readonly sideEffect: ToolSideEffect;
  readonly reason: string;
}

export interface PermissionPolicy {
  check(request: PermissionRequest): PermissionDecision;
}

export interface PermissionDecision {
  readonly allowed: boolean;
  readonly reason: string;
}

export interface GuardrailResult {
  readonly allowed: boolean;
  readonly reason: string;
}

export interface Verifier {
  verify(output: string): GuardrailResult;
}
`;
}

function traceTs(): string {
  return `import type { TraceEvent, TraceSink } from './types.js';

export function createTraceSink(): TraceSink {
  const events: TraceEvent[] = [];
  return {
    record(event) {
      events.push({ ...event, timestamp: new Date().toISOString() });
    },
    list() {
      return [...events];
    },
  };
}
`;
}

function artifactsTs(): string {
  return `import type { Artifact, ArtifactStore } from './types.js';

export function createArtifactStore(): ArtifactStore {
  const artifacts: Artifact[] = [];
  return {
    write(path, content) {
      artifacts.push({ path, content });
    },
    list() {
      return [...artifacts];
    },
  };
}
`;
}

function guardrailsTs(): string {
  return `import type { GuardrailResult } from './types.js';

export function requireNonEmptyOutput(output: string): GuardrailResult {
  const allowed = output.trim().length > 0;
  return {
    allowed,
    reason: allowed ? 'Output is non-empty.' : 'Output is empty.',
  };
}
`;
}

function modelProviderTs(): string {
  return `import type { ModelProvider } from './types.js';

export function createNotConfiguredModelProvider(): ModelProvider {
  return {
    async generate() {
      throw new Error('MODEL_PROVIDER_NOT_CONFIGURED: inject a real ModelProvider before running this application.');
    },
  };
}
`;
}

function permissionsTs(): string {
  return `import type { PermissionPolicy } from './types.js';

export function createDefaultPermissionPolicy(): PermissionPolicy {
  return {
    check(request) {
      if (request.sideEffect === 'none') {
        return { allowed: true, reason: 'Pure tool execution is allowed.' };
      }
      return {
        allowed: false,
        reason: \`Tool \${request.toolId} requires explicit permission for side effect: \${request.sideEffect}.\`,
      };
    },
  };
}
`;
}

function verificationTs(): string {
  return `import { requireNonEmptyOutput } from './guardrails.js';
import type { Verifier } from './types.js';

export function createDefaultVerifier(): Verifier {
  return {
    verify(output) {
      return requireNonEmptyOutput(output);
    },
  };
}
`;
}

function toolsTs(manifest: AquaProjectManifest): string {
  const imports: string[] = [];
  const toolNames: string[] = [];
  if (manifest.modules.tools.includes('artifact-recorder')) {
    imports.push("import { artifactRecorderTool } from '../tools/artifact-recorder.js';");
    toolNames.push('artifactRecorderTool');
  }

  return `import type { Tool, ToolDescriptor, ToolRegistry } from './types.js';
${imports.join('\n')}

export function createToolRegistry(): ToolRegistry {
  const tools: readonly Tool[] = [${toolNames.join(', ')}];
  const byId = new Map<string, Tool>(tools.map((tool) => [tool.id, tool]));
  return {
    get(id) {
      return byId.get(id);
    },
    list() {
      return [...byId.values()];
    },
    describe(): readonly ToolDescriptor[] {
      return tools.map((tool) => ({
        id: tool.id,
        description: tool.description,
        sideEffect: tool.sideEffect,
      }));
    },
  };
}
`;
}

function runnerTs(): string {
  return `import { createArtifactStore } from './artifacts.js';
import { createDefaultPermissionPolicy } from './permissions.js';
import { createToolRegistry } from './tools.js';
import { createTraceSink } from './trace.js';
import { createDefaultVerifier } from './verification.js';
import type { AgentContext, HarnessRunInput, HarnessRunResult, ModelProvider, Workflow } from './types.js';

export interface RunnerOptions {
  readonly modelProvider: ModelProvider;
  readonly workflow: Workflow;
}

export function createRunner(options: RunnerOptions) {
  return {
    async run(input: HarnessRunInput): Promise<HarnessRunResult> {
      const context: AgentContext = {
        trace: createTraceSink(),
        artifacts: createArtifactStore(),
        tools: createToolRegistry(),
        permissions: createDefaultPermissionPolicy(),
        verifier: createDefaultVerifier(),
        modelProvider: options.modelProvider,
      };
      context.trace.record({ type: 'run.started', message: 'Harness run started.' });
      const result = await options.workflow.run(input, context);
      context.trace.record({ type: 'run.completed', message: 'Harness run completed.', metadata: { success: result.success } });
      return {
        ...result,
        trace: context.trace.list(),
        artifacts: context.artifacts.list(),
      };
    },
  };
}
`;
}

function workflowTs(manifest: AquaProjectManifest): string {
  const imports = manifest.modules.agents.map((agent) => `import { ${toExportedAgent(agent)} } from '../agents/${agent}.js';`).join('\n');
  const agentRefs = manifest.modules.agents.map((agent) => toExportedAgent(agent)).join(', ');

  return `${imports}
import type { Agent, AgentContext, HarnessRunInput, HarnessRunResult, Workflow } from '../harness/types.js';

const agents: readonly Agent[] = [${agentRefs}];

export function createPlanExecuteVerifyWorkflow(): Workflow {
  return {
    async run(input: HarnessRunInput, context: AgentContext): Promise<HarnessRunResult> {
      let current = input.input;
      let lastErrorCode: string | undefined;

      for (const agent of agents) {
        context.trace.record({ type: 'agent.started', message: \`Agent \${agent.id} started.\` });
        const result = await agent.run(current, context);
        context.trace.record({ type: 'agent.completed', message: \`Agent \${agent.id} completed.\`, metadata: { success: result.success, errorCode: result.errorCode } });
        if (!result.success) {
          return {
            success: false,
            output: result.output,
            ...(result.errorCode ? { errorCode: result.errorCode } : {}),
            trace: context.trace.list(),
            artifacts: context.artifacts.list(),
          };
        }
        current = result.output;
        lastErrorCode = result.errorCode;
      }

      const verification = context.verifier.verify(current);
      context.trace.record({ type: 'verification.completed', message: verification.reason });

      return {
        success: verification.allowed,
        output: current,
        ...(!verification.allowed && lastErrorCode ? { errorCode: lastErrorCode } : {}),
        trace: context.trace.list(),
        artifacts: context.artifacts.list(),
      };
    },
  };
}
`;
}

function artifactRecorderToolTs(): string {
  return `import type { Tool } from '../harness/types.js';

export const artifactRecorderTool: Tool = {
  id: 'artifact-recorder',
  description: 'Record an in-memory artifact for downstream inspection.',
  sideEffect: 'none',
  async execute(input, context) {
    const content = typeof input === 'string' ? input : JSON.stringify(input, null, 2);
    context.artifacts.write('artifact.txt', content);
    return { path: 'artifact.txt' };
  },
};
`;
}

function agentTs(agent: string): string {
  return `import type { Agent } from '../harness/types.js';

export const ${toExportedAgent(agent)}: Agent = {
  id: '${agent}',
  role: '${agent}',
  instructions: 'Implement the ${agent} role for this application. Keep this prompt specific to the domain before production use.',
  async run(input, context) {
    try {
      const response = await context.modelProvider.generate({
        agentId: this.id,
        role: this.role,
        instructions: this.instructions,
        input,
        availableTools: context.tools.describe(),
      });
      return {
        success: true,
        output: response.text,
      };
    } catch (error) {
      const message = error instanceof Error ? error.message : String(error);
      const errorCode = message.startsWith('MODEL_PROVIDER_NOT_CONFIGURED') ? 'MODEL_PROVIDER_NOT_CONFIGURED' : 'AGENT_MODEL_ERROR';
      return {
        success: false,
        output: message,
        errorCode,
      };
    }
  },
};
`;
}

function fakeModelProviderTs(): string {
  return `import type { ModelProvider } from '../../src/harness/types.js';

export function createFakeModelProvider(prefix = 'verified-test-output'): ModelProvider {
  return {
    async generate(request) {
      return {
        text: \`\${prefix}:\${request.agentId}:\${request.input}\`,
      };
    },
  };
}
`;
}

function smokeTestTs(manifest: AquaProjectManifest): string {
  return `import test from 'node:test';
import assert from 'node:assert/strict';
import { run } from '../src/index.js';
import { createFakeModelProvider } from './fakes/fake-model-provider.js';

test('${manifest.projectName} fails honestly without a configured model provider', async () => {
  const result = await run('hello');
  assert.equal(result.success, false);
  assert.equal(result.errorCode, 'MODEL_PROVIDER_NOT_CONFIGURED');
});

test('${manifest.projectName} harness runs with an explicit test model provider', async () => {
  const result = await run('hello', { modelProvider: createFakeModelProvider() });
  assert.equal(result.success, true);
  assert.match(result.output, /verified-test-output/);
  assert.ok(result.trace.some((event) => event.type === 'verification.completed'));
});
`;
}

function toExportedAgent(value: string): string {
  return `${toIdentifier(value)}Agent`;
}

function toIdentifier(value: string): string {
  const pascal = value.replace(/(^|[-_])([a-zA-Z0-9])/g, (_match, _prefix: string, char: string) => char.toUpperCase());
  return pascal.replace(/^[A-Z]/, (char) => char.toLowerCase());
}
