import type { AquaFilePlan, AquaProjectManifest } from './types.js';

export function renderProjectFiles(manifest: AquaProjectManifest): readonly AquaFilePlan[] {
  const files: AquaFilePlan[] = [
    file('.aqua/project.json', `${JSON.stringify(manifest, null, 2)}\n`),
    file('package.json', packageJson(manifest)),
    file('pnpm-workspace.yaml', 'packages: []\n'),
    file('tsconfig.json', tsconfigJson()),
    file('README.md', readme(manifest)),
    file('src/index.ts', indexTs()),
    file('src/harness/types.ts', harnessTypesTs()),
    file('src/harness/trace.ts', traceTs()),
    file('src/harness/artifacts.ts', artifactsTs()),
    file('src/harness/guardrails.ts', guardrailsTs()),
    file('src/harness/permissions.ts', permissionsTs()),
    file('src/harness/verification.ts', verificationTs()),
    file('src/harness/tools.ts', toolsTs(manifest)),
    file('src/harness/runner.ts', runnerTs()),
    file('src/workflows/plan-execute-verify.ts', workflowTs(manifest)),
    file('src/tools/echo.ts', echoToolTs()),
    ...manifest.modules.agents.map((agent) => file(`src/agents/${agent}.ts`, agentTs(agent))),
    file('tests/smoke.test.ts', smokeTestTs(manifest)),
  ];

  if (manifest.modules.tools.includes('artifact-writer')) {
    files.push(file('src/tools/artifact-writer.ts', artifactWriterToolTs()));
  }

  return files;
}

function file(relativePath: string, content: string): AquaFilePlan {
  return { relativePath, content };
}

function packageJson(manifest: AquaProjectManifest): string {
  return `${JSON.stringify({
    name: manifest.projectName.toLowerCase().replace(/_/g, '-'),
    version: '0.1.0',
    private: true,
    type: 'module',
    scripts: {
      build: 'tsc -p tsconfig.json',
      typecheck: 'tsc -p tsconfig.json --noEmit',
      test: 'tsc -p tsconfig.json && node --test dist/tests/*.test.js',
      smoke: 'tsc -p tsconfig.json && node dist/src/index.js',
    },
    devDependencies: {
      '@types/node': '^20.11.0',
      typescript: '^5.3.0',
    },
  }, null, 2)}\n`;
}

function tsconfigJson(): string {
  return `${JSON.stringify({
    compilerOptions: {
      target: 'ES2022',
      lib: ['ES2022'],
      module: 'NodeNext',
      moduleResolution: 'NodeNext',
      strict: true,
      exactOptionalPropertyTypes: true,
      noUncheckedIndexedAccess: true,
      noUnusedLocals: true,
      noUnusedParameters: true,
      noFallthroughCasesInSwitch: true,
      moduleDetection: 'force',
      forceConsistentCasingInFileNames: true,
      skipLibCheck: true,
      declaration: true,
      sourceMap: true,
      rootDir: '.',
      outDir: 'dist',
    },
    include: ['src/**/*.ts', 'tests/**/*.ts'],
  }, null, 2)}\n`;
}

function readme(manifest: AquaProjectManifest): string {
  return `# ${manifest.projectName}

Generated by AQUA as a modular TypeScript agent harness base.

## Contract

- Preset: \`${manifest.preset}\`
- Harness target: \`${manifest.harness}\`
- Agents: ${manifest.modules.agents.map((agent) => `\`${agent}\``).join(', ')}
- Tools: ${manifest.modules.tools.map((tool) => `\`${tool}\``).join(', ')}
- Workflows: ${manifest.modules.workflows.map((workflow) => `\`${workflow}\``).join(', ')}

The machine-readable project contract lives at \`.aqua/project.json\`. Keep CLI, Skill, and manual edits aligned with that file.

## Harness seams

- \`Agent\`: focused unit of behavior.
- \`Tool\`: deterministic capability with permission hooks.
- \`Workflow\`: owns control flow instead of hiding it inside model calls.
- \`TraceSink\`: records run, agent, and verification events.
- \`ArtifactStore\`: captures local outputs without requiring external services.
- \`PermissionPolicy\`: blocks side-effecting tools unless explicitly allowed.
- \`Verifier\`: checks final output before a run is considered successful.

## Verify

\`\`\`bash
${manifest.commands.install}
${manifest.commands.typecheck}
${manifest.commands.test}
${manifest.commands.smoke}
\`\`\`

Parallel agent execution is not simulated. If you target Codex, OpenCode, or Claude Code, add and verify a concrete harness adapter before claiming parallel dispatch.
`;
}

function indexTs(): string {
  return `import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { createRunner } from './harness/runner.js';
import { createPlanExecuteVerifyWorkflow } from './workflows/plan-execute-verify.js';

export { createRunner } from './harness/runner.js';
export type { Agent, AgentContext, AgentResult, HarnessRunInput, HarnessRunResult, Tool, Workflow } from './harness/types.js';

export async function run(input: string) {
  const runner = createRunner({
    workflow: createPlanExecuteVerifyWorkflow(),
  });
  return runner.run({ input });
}

const isMain = process.argv[1] ? fileURLToPath(import.meta.url) === path.resolve(process.argv[1]) : false;

if (isMain) {
  const input = process.argv.slice(2).join(' ') || 'smoke';
  const result = await run(input);
  console.log(JSON.stringify(result, null, 2));
}
`;
}

function harnessTypesTs(): string {
  return `export interface HarnessRunInput {
  readonly input: string;
}

export interface HarnessRunResult {
  readonly success: boolean;
  readonly output: string;
  readonly trace: readonly TraceEvent[];
  readonly artifacts: readonly Artifact[];
}

export interface AgentContext {
  readonly trace: TraceSink;
  readonly artifacts: ArtifactStore;
  readonly tools: ToolRegistry;
  readonly permissions: PermissionPolicy;
  readonly verifier: Verifier;
}

export interface Agent {
  readonly id: string;
  run(input: string, context: AgentContext): Promise<AgentResult>;
}

export interface AgentResult {
  readonly success: boolean;
  readonly output: string;
}

export interface Tool {
  readonly id: string;
  readonly description: string;
  readonly sideEffect: 'none' | 'local-filesystem' | 'network' | 'external-system';
  execute(input: unknown, context: AgentContext): Promise<unknown>;
}

export interface ToolRegistry {
  get(id: string): Tool | undefined;
  list(): readonly Tool[];
}

export interface TraceEvent {
  readonly type: 'run.started' | 'agent.started' | 'agent.completed' | 'verification.completed' | 'run.completed';
  readonly message: string;
  readonly timestamp: string;
  readonly metadata?: Record<string, unknown>;
}

export interface TraceSink {
  record(event: Omit<TraceEvent, 'timestamp'>): void;
  list(): readonly TraceEvent[];
}

export interface Artifact {
  readonly path: string;
  readonly content: string;
}

export interface ArtifactStore {
  write(path: string, content: string): void;
  list(): readonly Artifact[];
}

export interface Workflow {
  run(input: HarnessRunInput, context: AgentContext): Promise<HarnessRunResult>;
}

export interface PermissionRequest {
  readonly toolId: string;
  readonly sideEffect: Tool['sideEffect'];
  readonly reason: string;
}

export interface PermissionPolicy {
  check(request: PermissionRequest): PermissionDecision;
}

export interface PermissionDecision {
  readonly allowed: boolean;
  readonly reason: string;
}

export interface GuardrailResult {
  readonly allowed: boolean;
  readonly reason: string;
}

export interface Verifier {
  verify(output: string): GuardrailResult;
}
`;
}

function traceTs(): string {
  return `import type { TraceEvent, TraceSink } from './types.js';

export function createTraceSink(): TraceSink {
  const events: TraceEvent[] = [];
  return {
    record(event) {
      events.push({ ...event, timestamp: new Date().toISOString() });
    },
    list() {
      return [...events];
    },
  };
}
`;
}

function artifactsTs(): string {
  return `import type { Artifact, ArtifactStore } from './types.js';

export function createArtifactStore(): ArtifactStore {
  const artifacts: Artifact[] = [];
  return {
    write(path, content) {
      artifacts.push({ path, content });
    },
    list() {
      return [...artifacts];
    },
  };
}
`;
}

function guardrailsTs(): string {
  return `import type { GuardrailResult } from './types.js';

export function requireNonEmptyOutput(output: string): GuardrailResult {
  const allowed = output.trim().length > 0;
  return {
    allowed,
    reason: allowed ? 'Output is non-empty.' : 'Output is empty.',
  };
}
`;
}

function permissionsTs(): string {
  return `import type { PermissionPolicy } from './types.js';

export function createDefaultPermissionPolicy(): PermissionPolicy {
  return {
    check(request) {
      if (request.sideEffect === 'none') {
        return { allowed: true, reason: 'Pure tool execution is allowed.' };
      }
      return {
        allowed: false,
        reason: \`Tool \${request.toolId} requires explicit permission for side effect: \${request.sideEffect}.\`,
      };
    },
  };
}
`;
}

function verificationTs(): string {
  return `import { requireNonEmptyOutput } from './guardrails.js';
import type { Verifier } from './types.js';

export function createDefaultVerifier(): Verifier {
  return {
    verify(output) {
      return requireNonEmptyOutput(output);
    },
  };
}
`;
}

function toolsTs(manifest: AquaProjectManifest): string {
  const imports = ["import { echoTool } from '../tools/echo.js';"];
  const toolNames = ['echoTool'];
  if (manifest.modules.tools.includes('artifact-writer')) {
    imports.push("import { artifactWriterTool } from '../tools/artifact-writer.js';");
    toolNames.push('artifactWriterTool');
  }

  return `import type { Tool, ToolRegistry } from './types.js';
${imports.join('\n')}

export function createToolRegistry(): ToolRegistry {
  const tools: readonly Tool[] = [${toolNames.join(', ')}];
  const byId = new Map<string, Tool>(tools.map((tool) => [tool.id, tool]));
  return {
    get(id) {
      return byId.get(id);
    },
    list() {
      return [...byId.values()];
    },
  };
}
`;
}

function runnerTs(): string {
  return `import { createArtifactStore } from './artifacts.js';
import { createDefaultPermissionPolicy } from './permissions.js';
import { createToolRegistry } from './tools.js';
import { createTraceSink } from './trace.js';
import { createDefaultVerifier } from './verification.js';
import type { AgentContext, HarnessRunInput, HarnessRunResult, Workflow } from './types.js';

export interface RunnerOptions {
  readonly workflow: Workflow;
}

export function createRunner(options: RunnerOptions) {
  return {
    async run(input: HarnessRunInput): Promise<HarnessRunResult> {
      const context: AgentContext = {
        trace: createTraceSink(),
        artifacts: createArtifactStore(),
        tools: createToolRegistry(),
        permissions: createDefaultPermissionPolicy(),
        verifier: createDefaultVerifier(),
      };
      context.trace.record({ type: 'run.started', message: 'Harness run started.' });
      const result = await options.workflow.run(input, context);
      context.trace.record({ type: 'run.completed', message: 'Harness run completed.', metadata: { success: result.success } });
      return {
        ...result,
        trace: context.trace.list(),
        artifacts: context.artifacts.list(),
      };
    },
  };
}
`;
}

function workflowTs(manifest: AquaProjectManifest): string {
  const firstAgent = manifest.modules.agents[0];
  if (!firstAgent) {
    throw new Error('Preset must define at least one agent.');
  }
  return `import { ${toExportedAgent(firstAgent)} } from '../agents/${firstAgent}.js';
import type { Agent, AgentContext, HarnessRunInput, HarnessRunResult, Workflow } from '../harness/types.js';

const agents: readonly Agent[] = [${toExportedAgent(firstAgent)}];

export function createPlanExecuteVerifyWorkflow(): Workflow {
  return {
    async run(input: HarnessRunInput, context: AgentContext): Promise<HarnessRunResult> {
      const primaryAgent = agents.at(0);
      if (!primaryAgent) {
        return {
          success: false,
          output: 'No agent is configured for this workflow.',
          trace: context.trace.list(),
          artifacts: context.artifacts.list(),
        };
      }
      context.trace.record({ type: 'agent.started', message: \`Agent \${primaryAgent.id} started.\` });
      const result = await primaryAgent.run(input.input, context);
      context.trace.record({ type: 'agent.completed', message: \`Agent \${primaryAgent.id} completed.\`, metadata: { success: result.success } });

      const verification = context.verifier.verify(result.output);
      const verified = result.success && verification.allowed;
      context.trace.record({ type: 'verification.completed', message: verification.reason });

      return {
        success: verified,
        output: result.output,
        trace: context.trace.list(),
        artifacts: context.artifacts.list(),
      };
    },
  };
}
`;
}

function echoToolTs(): string {
  return `import type { Tool } from '../harness/types.js';

export const echoTool: Tool = {
  id: 'echo',
  description: 'Return the input unchanged.',
  sideEffect: 'none',
  async execute(input) {
    return input;
  },
};
`;
}

function artifactWriterToolTs(): string {
  return `import type { Tool } from '../harness/types.js';

export const artifactWriterTool: Tool = {
  id: 'artifact-writer',
  description: 'Write an in-memory artifact for downstream inspection.',
  sideEffect: 'local-filesystem',
  async execute(input, context) {
    const permission = context.permissions.check({
      toolId: 'artifact-writer',
      sideEffect: 'local-filesystem',
      reason: 'The workflow requested an artifact write.',
    });
    if (!permission.allowed) {
      throw new Error(permission.reason);
    }
    const content = typeof input === 'string' ? input : JSON.stringify(input, null, 2);
    context.artifacts.write('artifact.txt', content);
    return { path: 'artifact.txt' };
  },
};
`;
}

function agentTs(agent: string): string {
  return `import type { Agent } from '../harness/types.js';

export const ${toExportedAgent(agent)}: Agent = {
  id: '${agent}',
  async run(input, context) {
    const echo = context.tools.get('echo');
    const echoed = echo ? await echo.execute(input, context) : input;
    return {
      success: true,
      output: \`[${agent}] \${String(echoed)}\`,
    };
  },
};
`;
}

function smokeTestTs(manifest: AquaProjectManifest): string {
  return `import test from 'node:test';
import assert from 'node:assert/strict';
import { run } from '../src/index.js';

test('${manifest.projectName} smoke workflow returns verified output and trace', async () => {
  const result = await run('hello');
  assert.equal(result.success, true);
  assert.match(result.output, /hello/);
  assert.ok(result.trace.some((event) => event.type === 'verification.completed'));
});
`;
}

function toExportedAgent(value: string): string {
  return `${toIdentifier(value)}Agent`;
}

function toIdentifier(value: string): string {
  const pascal = value.replace(/(^|[-_])([a-zA-Z0-9])/g, (_match, _prefix: string, char: string) => char.toUpperCase());
  return pascal.replace(/^[A-Z]/, (char) => char.toLowerCase());
}
