import chalk from 'chalk';
import fs from 'fs-extra';
import path from 'path';
import { logger } from '../utils/logger.js';

interface GenerateOptions {
  output?: string;
  force?: boolean;
}

export async function generateCommand(options: GenerateOptions): Promise<void> {
  const configPath = path.resolve(process.cwd(), 'aqua.config.json');

  if (!fs.existsSync(configPath)) {
    logger.error('Not an AQUA project. Run "aqua create" first.');
    return;
  }

  const config = await fs.readJson(configPath);
  const outputDir = path.resolve(process.cwd(), options.output || './workbench');

  logger.header('Generating Workbench');

  if (fs.existsSync(outputDir) && !options.force) {
    logger.error(`Output directory "${outputDir}" already exists. Use --force to overwrite.`);
    return;
  }

  logger.info(`Output directory: ${chalk.gray(outputDir)}`);

  if (options.force && fs.existsSync(outputDir)) {
    logger.info('Removing existing directory...');
    await fs.remove(outputDir);
  }

  await fs.ensureDir(outputDir);

  const packageJson = {
    name: `${(config.projectName as string).replace(/[^a-z0-9]/gi, '-')}-workbench`,
    version: '0.1.0',
    type: 'module',
    main: './dist/index.js',
    types: './dist/index.d.ts',
    exports: {
      '.': {
        import: './dist/index.js',
        types: './dist/index.d.ts',
      },
    },
    scripts: {
      build: 'tsc',
      dev: 'tsx src/index.ts',
    },
    dependencies: {
      zod: '^3.22.0',
    },
  };

  await fs.writeJson(path.join(outputDir, 'package.json'), packageJson, { spaces: 2 });
  logger.success('Created package.json');

  const tsconfig = {
    extends: '../../tsconfig.json',
    compilerOptions: {
      outDir: './dist',
      rootDir: './src',
    },
    include: ['src/**/*'],
  };

  await fs.writeJson(path.join(outputDir, 'tsconfig.json'), tsconfig, { spaces: 2 });
  logger.success('Created tsconfig.json');

  await fs.ensureDir(path.join(outputDir, 'src'));

  const indexContent = `import { createWorkbench, type WorkbenchConfig } from '@aqua/workbench';

const config: WorkbenchConfig = ${JSON.stringify(
    {
      agents: config.agents,
      skills: config.skills,
      llm: config.llm,
    },
    null,
    2
  )};

export const workbench = createWorkbench(config);

export type { WorkbenchConfig } from '@aqua/workbench';

export async function initialize() {
  await workbench.initialize();
  return workbench;
}

export async function shutdown() {
  await workbench.shutdown();
}

export const agents = {
  list: () => workbench.listAgents(),
  get: (id: string) => workbench.getAgent(id),
  execute: (id: string, input: unknown) => workbench.execute(id, input),
};

export const skills = {
  execute: (id: string, params: Record<string, unknown>, context?: Record<string, unknown>) =>
    workbench.executeSkill(id, params, context as any),
};
`;

  await fs.writeFile(path.join(outputDir, 'src/index.ts'), indexContent);
  logger.success('Created src/index.ts');

  const readmeContent = `# Workbench

Generated by AQUA.

## Usage

\`\`\`typescript
import { initialize, agents, skills } from './dist/index.js';

const wb = await initialize();

// List agents
const agentList = agents.list();

// Execute agent
const result = await agents.execute('router', 'Hello');

// Execute skill
const skillResult = await skills.execute('calculator', { expression: '2 + 2' });
\`\`\`
`;

  await fs.writeFile(path.join(outputDir, 'README.md'), readmeContent);
  logger.success('Created README.md');

  logger.header('Generation complete!');
  logger.info(`\nNext steps:`);
  logger.bullet(`cd ${outputDir}`);
  logger.bullet(`pnpm install`);
  logger.bullet(`pnpm run build`);
}
